services:
  app:
    image: "infobarbosa/influxproducer"
    container_name: influxproducer
    environment:
      - INFLUXDB_HOST=influxdb-demo
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=3y1c3NnlmA1kA061YlROSO0gE5a1ppH_1Ig5HSMCsCX3VKF6zkrBwAtC-Hr6c_TTU8B9kwYOPphDq6hwyw5tLw==
      - INFLUXDB_ORG=infobarbosa
      - INFLUXDB_BUCKET=ecommerce
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:latest
    container_name: influxdb-demo
    volumes:
      - ./assets/certificates/ssl/:/etc/ssl/
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=barbosa
      - DOCKER_INFLUXDB_INIT_PASSWORD=mudar123
      - DOCKER_INFLUXDB_INIT_ORG=infobarbosa
      - DOCKER_INFLUXDB_INIT_BUCKET=ecommerce
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=3y1c3NnlmA1kA061YlROSO0gE5a1ppH_1Ig5HSMCsCX3VKF6zkrBwAtC-Hr6c_TTU8B9kwYOPphDq6hwyw5tLw==
      - INFLUXD_TLS_CERT=/etc/ssl/influxdb.crt
      - INFLUXD_TLS_KEY=/etc/ssl/influxdb.key
    ports:
      - "8086:8086"
