services:
  influxdb:
    image: influxdb:3-core
    container_name: influxdb-demo
    command: serve --object-store file --data-dir /var/lib/influxdb3 --without-auth
    ports:
      - "8086:8086"
    volumes:
      - influxdb3-data:/var/lib/influxdb3

  influxproducer:
    image: alpine/curl
    container_name: influxproducer
    environment:
      - INFLUXDB_URL=http://influxdb-demo:8086
      - DATABASE=ecommerce
    volumes:
      - ./assets/scripts/pedidos.sh:/pedidos.sh:ro
    command: ["/bin/sh", "/pedidos.sh"]
    depends_on:
      - influxdb
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb

volumes:
  influxdb3-data:
