services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb-demo
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=barbosa
      - DOCKER_INFLUXDB_INIT_PASSWORD=mudar123
      - DOCKER_INFLUXDB_INIT_ORG=infobarbosa
      - DOCKER_INFLUXDB_INIT_BUCKET=ecommerce
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=3y1c3NnlmA1kA061YlROSO0gE5a1ppH_1Ig5HSMCsCX3VKF6zkrBwAtC-Hr6c_TTU8B9kwYOPphDq6hwyw5tLw==
    ports:
      - "8086:8086"
  influxproducer:
    image: "infobarbosa/influxproducer"
    container_name: influxproducer
    environment:
      - INFLUXDB_HOST=influxdb-demo
      - INFLUXDB_URL=http://influxdb-demo:8086
      - INFLUXDB_TOKEN=3y1c3NnlmA1kA061YlROSO0gE5a1ppH_1Ig5HSMCsCX3VKF6zkrBwAtC-Hr6c_TTU8B9kwYOPphDq6hwyw5tLw==
      - INFLUXDB_ORG=infobarbosa
      - INFLUXDB_BUCKET=ecommerce
    depends_on:
      - influxdb
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
    links:
      - influxdb



