services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb-demo
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "barbosa"
      DOCKER_INFLUXDB_INIT_PASSWORD: "mudar123"
      DOCKER_INFLUXDB_INIT_ORG: "infobarbank"
      DOCKER_INFLUXDB_INIT_BUCKET: "demo"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "3y1c3NnlmA1kA061YlROSO0gE5a1ppH_1Ig5HSMCsCX3VKF6zkrBwAtC-Hr6c_TTU8B9kwYOPphDq6hwyw5tLw=="
    ports:
      - "8086:8086"
